name: ReviversTwo
version: '2'
main: net.revivers.reviverstwo.ReviversTwo
authors: [ sdap ]
depend: [ Vault, NametagEdit ]
commands:
  match:
    description: Create a match.
    permission: revivers.match
  debug:
    description: Debug tools.
    permission: revivers.debug
  spectate:
    description: Spectate players with this command.
  revivers:
    description: Shows credits of the Revivers plugin.
  leave:
    description: Leave your current match.